/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Case
         * @description Return the authorized safe surface for one case, preview regenerated on read.
         */
        get: operations["read_case_v1_cases__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{case_id}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Propose Action
         * @description Create one ``PROPOSE_ACTION`` operation and hand it over. No model is called here.
         */
        post: operations["propose_action_v1_cases__case_id__actions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{case_id}/actions/{action_id}/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Action
         * @description Record one immutable human decision about one immutable proposal.
         */
        post: operations["approve_action_v1_cases__case_id__actions__action_id__approvals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{case_id}/actions/{action_id}/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Execution
         * @description Create one ``SEND_ACTION`` operation and hand it over. No SES call happens here.
         *
         *     ``202`` and a poll, for the same reason the proposal route returns one: an external call is
         *     not something an HTTP request should hold a connection open for. The caller reads the
         *     outcome through the existing operation poll and the existing case surface.
         */
        post: operations["start_execution_v1_cases__case_id__actions__action_id__executions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{case_id}/actions/{action_id}/invalidation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invalidate Action
         * @description Withdraw an approval, or clear a terminal failure, freeing the case for a new proposal.
         *
         *     Refused for ``SENDING``, ``SENT``, and ``SEND_UNKNOWN``, each for its own reason: a send in
         *     flight cannot be taken back, a sent message cannot be recalled, and an ambiguous outcome is
         *     a quarantine only reconciliation resolves.
         */
        post: operations["invalidate_action_v1_cases__case_id__actions__action_id__invalidation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{case_id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Case Audit
         * @description Page one case's safe audit trail, presenter-only, in occurrence order.
         */
        get: operations["read_case_audit_v1_cases__case_id__audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{case_id}/commitments/{commitment_id}/verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Commitment
         * @description Record one affected contributor's decision. The only source that may resolve a case.
         */
        post: operations["verify_commitment_v1_cases__case_id__commitments__commitment_id__verification_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{case_id}/investigation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Investigation
         * @description Presenter-only. Creates nothing; the private half of ``PrivacyBoundaryCompare``.
         */
        get: operations["read_investigation_v1_cases__case_id__investigation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{case_id}/investigations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Investigation
         * @description Create one ``INVESTIGATE`` operation and hand it over. No model is called here.
         */
        post: operations["start_investigation_v1_cases__case_id__investigations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{case_id}/mandates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Propose Mandates
         * @description Accept a candidate case and ask every contributor it names for a mandate.
         */
        post: operations["propose_mandates_v1_cases__case_id__mandates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{case_id}/mandates/{mandate_id}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide Mandate
         * @description Record one immutable authorization decision by the contributor who owns the mandate.
         */
        post: operations["decide_mandate_v1_cases__case_id__mandates__mandate_id__decisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{case_id}/views": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compile View
         * @description Compile one safe view, or refuse deterministically. No model is called here.
         */
        post: operations["compile_view_v1_cases__case_id__views_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/contributors/{contributor_id}/mandates/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Current Mandate
         * @description Return one contributor's mandate thread for one case.
         *
         *     A resident may read only their own. Asking for somebody else's answers ``404`` rather than
         *     ``403``, and identically to an identifier that names nobody: a caller who could tell those
         *     apart could enumerate which contributors exist and which of them have mandates in a case
         *     they cannot otherwise see.
         */
        get: operations["read_current_mandate_v1_contributors__contributor_id__mandates_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/demo/clock/advance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Advance Demo Clock
         * @description Move the logical clock, then invoke the same watcher with the same event.
         *
         *     The event this route builds is derived from the commitment's own identity and generation --
         *     it is the value the schedule would have carried -- and the watcher re-verifies every field of
         *     it against the strongly loaded row. So a presenter can make a deadline arrive and can change
         *     nothing else: both commitment outcomes still require a contributor.
         */
        post: operations["advance_demo_clock_v1_demo_clock_advance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/demo/corpus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Demo Corpus
         * @description Serve the exact seeded corpus, resolved into the shape ingest already accepts.
         */
        get: operations["read_demo_corpus_v1_demo_corpus_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/demo/external-replies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deliver External Reply
         * @description Deliver one reviewed fixture through the trust boundary, then start one extraction.
         */
        post: operations["deliver_external_reply_v1_demo_external_replies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/demo/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Demo
         * @description Delete-and-seed the demo namespace, idempotently, against local adapters.
         */
        post: operations["reset_demo_v1_demo_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Feed
         * @description Return one page of ambient messages with any discovered-pattern signal attached.
         */
        get: operations["read_feed_v1_feed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ingest/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Messages
         * @description Persist a batch of ambient messages and start one Monitor operation over it.
         */
        post: operations["ingest_messages_v1_ingest_messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/operations/{operation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Operation
         * @description Return the status of one durable operation.
         *
         *     Agent output is never returned here. ``result_refs`` names the case the validated result
         *     was applied to, and the caller reads it through the endpoint that authorizes that case.
         *
         *     The presenter may inspect any operation, because operating the demo means watching work
         *     that other personas started. Everyone else may inspect only their own: an operation
         *     identifier is a random UUID, but guessing difficulty is not an authorization boundary, so
         *     the actor hash on the record is compared to the caller's.
         */
        get: operations["read_operation_v1_operations__operation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Session
         * @description Resolve the calling persona. Cannot enumerate or name any other persona.
         */
        get: operations["read_session_v1_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdvanceDemoClockRequest
         * @description Which commitment to wake the watcher for, and how far to move the clock.
         */
        AdvanceDemoClockRequest: {
            /** Advance Seconds */
            advance_seconds: number;
            /**
             * Case Id
             * Format: uuid
             */
            case_id: string;
            /**
             * Commitment Id
             * Format: uuid
             */
            commitment_id: string;
        };
        /** AlternativeExplanationResponse */
        AlternativeExplanationResponse: {
            /** Cited Evidence Ids */
            cited_evidence_ids: string[];
            /** Cited Fact Ids */
            cited_fact_ids: string[];
            /** Cited Report Ids */
            cited_report_ids: string[];
            /** Description */
            description: string;
        };
        /**
         * ApprovalDecision
         * @enum {string}
         */
        ApprovalDecision: "APPROVED" | "REJECTED";
        /**
         * ApprovalRequest
         * @description The frozen approval body, and every field in it is something the human saw.
         *
         *     ``expected_action_status`` is deliberately absent: it named a status where the transaction
         *     conditions on a row version, and two ways to say "the thing I saw" is one too many.
         */
        ApprovalRequest: {
            decision: components["schemas"]["ApprovalDecision"];
            /**
             * Execution Id
             * Format: uuid
             */
            execution_id: string;
            /** Expected Execution Version */
            expected_execution_version: number;
            /** Preview Hash */
            preview_hash: string;
            /** Proposal Hash */
            proposal_hash: string;
            /** View Hash */
            view_hash: string;
        };
        /** ApprovalResponse */
        ApprovalResponse: {
            /** Approval Hash */
            approval_hash: string;
            /**
             * Approval Id
             * Format: uuid
             */
            approval_id: string;
            /** Authorization Version */
            authorization_version: number;
            /** Case State */
            case_state: string;
            /** Case Version */
            case_version: number;
            /** Decision */
            decision: string;
            /**
             * Execution Id
             * Format: uuid
             */
            execution_id: string;
            /** Execution State */
            execution_state: string;
            /** Execution Version */
            execution_version: number;
            /** Expires At */
            expires_at: string;
            /** Pointer Status */
            pointer_status: string;
            /** Replayed */
            replayed: boolean;
        };
        /** AssessmentResponse */
        AssessmentResponse: {
            /** Alternative Explanations */
            alternative_explanations: components["schemas"]["AlternativeExplanationResponse"][];
            /** Assessment Hash */
            assessment_hash: string;
            /**
             * Assessment Id
             * Format: uuid
             */
            assessment_id: string;
            /** Based On Case Version */
            based_on_case_version: number;
            /** Contradictions */
            contradictions: components["schemas"]["ContradictionResponse"][];
            /** Created At */
            created_at: string;
            /** Findings */
            findings: components["schemas"]["FindingResponse"][];
            /** Independent Source Count */
            independent_source_count: number;
            /** Is Corroborated */
            is_corroborated: boolean;
            /** Linkage Decision */
            linkage_decision: string;
            /** Recommended Disposition */
            recommended_disposition: string;
        };
        /** AttachmentThumbnailResponse */
        AttachmentThumbnailResponse: {
            /** Caption */
            caption: string | null;
            /** Evidence Id */
            evidence_id: string;
            /** Media Type */
            media_type: string;
        };
        /** AuditDetailsResponse */
        AuditDetailsResponse: {
            /** Count */
            count: number | null;
            /** Rule Id */
            rule_id: string | null;
        };
        /** AuditEntityRefResponse */
        AuditEntityRefResponse: {
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /** Entity Type */
            entity_type: string;
            /** Version */
            version: number | null;
        };
        /** AuditEventResponse */
        AuditEventResponse: {
            /** Actor Type */
            actor_type: string;
            /**
             * Audit Event Id
             * Format: uuid
             */
            audit_event_id: string;
            /** Causation Id */
            causation_id: string | null;
            /**
             * Correlation Id
             * Format: uuid
             */
            correlation_id: string;
            /** Decision */
            decision: string;
            /** Entity Refs */
            entity_refs: components["schemas"]["AuditEntityRefResponse"][];
            /** Event Type */
            event_type: string;
            /** Input Hash */
            input_hash: string | null;
            /** Occurred At */
            occurred_at: string;
            /** Output Hash */
            output_hash: string | null;
            /** Reason Codes */
            reason_codes: string[];
            safe_details: components["schemas"]["AuditDetailsResponse"];
        };
        /** AuditPageResponse */
        AuditPageResponse: {
            /** Items */
            items: components["schemas"]["AuditEventResponse"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** CaseHeaderResponse */
        CaseHeaderResponse: {
            /** Authorization Version */
            authorization_version: number;
            /**
             * Case Id
             * Format: uuid
             */
            case_id: string;
            /** Corroboration Source Count */
            corroboration_source_count: number;
            /** Issue Type */
            issue_type: string;
            /** State */
            state: string;
            /** State Reason Code */
            state_reason_code: string;
            /** Title */
            title: string | null;
            /** Version */
            version: number;
        };
        /**
         * CaseSurfaceResponse
         * @description The frozen case surface: the Phase 7 section plus the five Phase 10 completes.
         *
         *     ``current_action`` is ``null`` when the case has never held a proposal. That is a state, not
         *     an error: a case in ``READY_FOR_ACTION`` legitimately has no action yet.
         *
         *     For ``case_approver``, ``case.title``, ``evidence_summary``, and ``privacy_counts`` are
         *     omitted -- the private title/fact labels and privacy exclusion reasons stay presenter-only,
         *     and only view/action-safe fields remain.
         */
        CaseSurfaceResponse: {
            case: components["schemas"]["CaseHeaderResponse"] | null;
            /**
             * Case Id
             * Format: uuid
             */
            case_id: string;
            /** Commitments */
            commitments: components["schemas"]["CommitmentSafeResponse"][];
            current_action: components["schemas"]["CurrentActionResponse"] | null;
            current_shareable_view: components["schemas"]["ShareableCaseViewBody"] | null;
            /** Evidence Summary */
            evidence_summary: components["schemas"]["EvidenceSummaryRowResponse"][] | null;
            privacy_counts: components["schemas"]["PrivacyCountsResponse"] | null;
        };
        /** CaveatProjection */
        CaveatProjection: {
            /** Export Fact Ids */
            export_fact_ids: string[];
            /** Text */
            text: string;
        };
        /** ChorusSignalResponse */
        ChorusSignalResponse: {
            /**
             * Candidate Case Id
             * Format: uuid
             */
            candidate_case_id: string;
            /** Label */
            label: string;
            /** Related Count */
            related_count: number;
            /** Status */
            status: string;
        };
        /**
         * ClaimProjection
         * @description One claim's own text and the short export-fact identifiers it cites.
         */
        ClaimProjection: {
            /** Export Fact Ids */
            export_fact_ids: string[];
            /** Text */
            text: string;
        };
        /**
         * CommitmentSafeResponse
         * @description Every field of ``Commitment`` except the four deliberately omitted ones.
         *
         *     ``source_evidence_id`` and ``due_event_id`` are the correlation/replay identities the
         *     watcher authenticates against, ``scheduler_name`` is transport addressing, and
         *     ``verification_evidence_id`` names a private artifact. ``case_id`` and ``schema_version``
         *     are already carried by the path and the response version.
         *
         *     ``schedule_status``/``schedule_last_error_code`` (P2-9) are the safe half of
         *     ``CommitmentScheduleProjection`` -- whether the one-time schedule exists yet, and the one
         *     closed code naming why not, never ``schedule_name`` or the due-event/replay identities the
         *     watcher itself authenticates against.
         */
        CommitmentSafeResponse: {
            /** Action Id */
            action_id: string | null;
            /** Action Text */
            action_text: string;
            /**
             * Commitment Id
             * Format: uuid
             */
            commitment_id: string;
            /** Created At */
            created_at: string;
            /** Due At */
            due_at: string;
            /** Obligor */
            obligor: string;
            /** Outcome Note */
            outcome_note: string | null;
            /** Schedule Generation */
            schedule_generation: number;
            /** Schedule Last Error Code */
            schedule_last_error_code: string | null;
            /** Schedule Status */
            schedule_status: string | null;
            /** Status */
            status: string;
            /** Updated At */
            updated_at: string;
            /** Verification Method */
            verification_method: string;
            /** Verified By Contributor Id */
            verified_by_contributor_id: string | null;
            /** Version */
            version: number;
        };
        /** CompileEvidenceResponse */
        CompileEvidenceResponse: {
            /** Derivative Sha256 */
            derivative_sha256: string | null;
            /** Export Handle Id */
            export_handle_id: string | null;
            /** Included */
            included: boolean;
            /** Reason Codes */
            reason_codes: string[];
            /**
             * Source Evidence Id
             * Format: uuid
             */
            source_evidence_id: string;
        };
        /** CompileExplanationResponse */
        CompileExplanationResponse: {
            /** Based On Case Version */
            based_on_case_version: number;
            /**
             * Compile Id
             * Format: uuid
             */
            compile_id: string;
            /** Compiler Version */
            compiler_version: string;
            /** Decision */
            decision: string;
            /** Evidence */
            evidence: components["schemas"]["CompileEvidenceResponse"][];
            /** Facts */
            facts: components["schemas"]["CompileFactResponse"][];
            /** Policy Version */
            policy_version: string;
            /** Reason Codes */
            reason_codes: string[];
            /** View Hash */
            view_hash: string | null;
            /** View Id */
            view_id: string | null;
        };
        /** CompileFactResponse */
        CompileFactResponse: {
            /** Export Fact Ids */
            export_fact_ids: string[];
            /**
             * Fact Id
             * Format: uuid
             */
            fact_id: string;
            /** Granted Scope */
            granted_scope: string | null;
            /** Included */
            included: boolean;
            /** Reason Codes */
            reason_codes: string[];
            /** Transformation Rule Id */
            transformation_rule_id: string | null;
        };
        /**
         * CompileViewRequest
         * @description The frozen ``CompileCommand``, minus everything the server decides for itself.
         *
         *     Namespace, community, and case come from the path and the deployment. The destination, the
         *     policy version, and the compiler contract version are configuration. What remains is what
         *     the caller genuinely chooses: which compile this is, which case version they believe they
         *     are compiling, and which of that case's facts and evidence they are asking about.
         */
        CompileViewRequest: {
            /**
             * Compile Id
             * Format: uuid
             */
            compile_id: string;
            /** Expected Case Version */
            expected_case_version: number;
            /**
             * Purpose
             * @constant
             */
            purpose: "REQUEST_ELEVATOR_REPAIR_AND_RESPONSE";
            /** Requested Evidence Ids */
            requested_evidence_ids?: string[];
            /** Requested Facts */
            requested_facts: components["schemas"]["RequestedFactBody"][];
        };
        /** CompileViewResponse */
        CompileViewResponse: {
            /**
             * Audit Event Id
             * Format: uuid
             */
            audit_event_id: string;
            /**
             * Compile Id
             * Format: uuid
             */
            compile_id: string;
            /**
             * Decision
             * @constant
             */
            decision: "ALLOW";
            /** Excluded */
            excluded: components["schemas"]["ExcludedFactBody"][];
            /** Included */
            included: components["schemas"]["IncludedFactBody"][];
            /** Replayed */
            replayed: boolean;
            view: components["schemas"]["ShareableCaseViewBody"] | null;
        };
        /** ContradictionResponse */
        ContradictionResponse: {
            /** Description */
            description: string;
            /** Materiality */
            materiality: string;
            /** Statement Fact Ids */
            statement_fact_ids: string[];
        };
        /** CurrentActionResponse */
        CurrentActionResponse: {
            /**
             * Action Id
             * Format: uuid
             */
            action_id: string;
            /** Approval Authorization Current */
            approval_authorization_current: boolean;
            /** Authorization Version */
            authorization_version: number;
            /** Case Version */
            case_version: number;
            /** Caveats */
            caveats: components["schemas"]["CaveatProjection"][];
            /** Claims */
            claims: components["schemas"]["ClaimProjection"][];
            execution: components["schemas"]["ExecutionProjection"];
            preview: components["schemas"]["RenderedPreviewProjection"];
            /** Proposal Hash */
            proposal_hash: string;
            /** Requested Action */
            requested_action: string;
            /** Status */
            status: string;
            /** Subject */
            subject: string;
            /** Tone */
            tone: string;
            /** View Hash */
            view_hash: string;
            /**
             * View Id
             * Format: uuid
             */
            view_id: string;
        };
        /**
         * DeliverFixtureReplyRequest
         * @description A closed body with exactly one field. There is nowhere to put a reply.
         */
        DeliverFixtureReplyRequest: {
            /** Fixture Id */
            fixture_id: string;
        };
        /** DemoClockView */
        DemoClockView: {
            /** Commitment Status */
            commitment_status: string | null;
            /** Logical Now */
            logical_now: string;
            /** Watcher Outcome */
            watcher_outcome: string;
        };
        /** DemoCorpusAttachmentResponse */
        DemoCorpusAttachmentResponse: {
            /** Byte Length */
            byte_length: number;
            /**
             * Evidence Id
             * Format: uuid
             */
            evidence_id: string;
            /** Media Type */
            media_type: string;
            /** Sha256 */
            sha256: string;
        };
        /**
         * DemoCorpusMessageResponse
         * @description One message in exactly the shape `POST /ingest/messages` accepts for a single item.
         *
         *     So the frontend never needs to reshape this response before replaying it — see
         *     `DemoCorpusResponse` (P2-7).
         */
        DemoCorpusMessageResponse: {
            /**
             * Adapter
             * @constant
             */
            adapter: "SYNTHETIC";
            /** Attachments */
            attachments: components["schemas"]["DemoCorpusAttachmentResponse"][];
            /** Channel Message Id */
            channel_message_id: string;
            /** Contributor Id */
            contributor_id: string | null;
            /** Sent At */
            sent_at: string;
            /** Text */
            text: string;
        };
        /**
         * DemoCorpusResponse
         * @description The immutable public ingestion input for the demo corpus, server-owned (P2-7).
         *
         *     Before this route, the only way a browser could replay the seeded corpus to trigger the
         *     Monitor was to mirror the checked-in fixture file as a frontend constant -- a second copy
         *     of `demo/fixtures/elevator-v1/{manifest,feed}.json` that could silently drift from the one
         *     the server actually seeds with. This route serves the same
         *     :class:`~chorus.infrastructure.fixtures.synthetic_feed.SyntheticAmbientAdapter` reset
         *     itself reads, so a fixture change on the server is picked up by the browser with no
         *     frontend change at all.
         *
         *     It carries no secret: every field here is exactly what `GET /feed` already shows a
         *     presenter after reset, resolved into the shape `POST /ingest/messages` accepts. It is
         *     presenter-only and wired only where `reset_demo` is (local/demo compositions), because it
         *     exists to serve the demo's own replay step and nothing else.
         */
        DemoCorpusResponse: {
            /**
             * Community Id
             * Format: uuid
             */
            community_id: string;
            /** Corpus Sha256 */
            corpus_sha256: string;
            /** Messages */
            messages: components["schemas"]["DemoCorpusMessageResponse"][];
            /** Seed Version */
            seed_version: string;
        };
        /** EvidenceSummaryRowResponse */
        EvidenceSummaryRowResponse: {
            /**
             * Contributor Id
             * Format: uuid
             */
            contributor_id: string;
            /** Evidence Ids */
            evidence_ids: string[];
            /** Evidence Status */
            evidence_status: string;
            /**
             * Fact Id
             * Format: uuid
             */
            fact_id: string;
            /** Fact Type */
            fact_type: string;
            /** Sensitivity */
            sensitivity: string;
            /** Status */
            status: string;
            /** Version */
            version: number;
        };
        /**
         * ExcludedFactBody
         * @description Why one requested fact did not travel. Private, and never part of the Action input.
         */
        ExcludedFactBody: {
            /**
             * Fact Id
             * Format: uuid
             */
            fact_id: string;
            /** Reason Codes */
            reason_codes: string[];
        };
        /**
         * ExecutionProjection
         * @description The safe execution projection. Its absent fields are absent on purpose (ADR-022 § 1).
         *
         *     ``approval_id`` is ``None`` at ``DRAFT`` and the row's own durable value from ``APPROVED``
         *     onward -- surfaced (P2-4) so a browser that approved a proposal and then reloaded before
         *     executing can read back the exact binding it needs for ``POST .../executions`` instead of
         *     depending on the one-time approval response it may no longer hold.
         */
        ExecutionProjection: {
            /** Approval Id */
            approval_id: string | null;
            /**
             * Execution Id
             * Format: uuid
             */
            execution_id: string;
            /** State */
            state: string;
            /** Version */
            version: number;
        };
        /**
         * ExecutionRequest
         * @description The frozen execute body. Three identifiers and a version; nothing steerable.
         */
        ExecutionRequest: {
            /**
             * Approval Id
             * Format: uuid
             */
            approval_id: string;
            /**
             * Execution Id
             * Format: uuid
             */
            execution_id: string;
            /** Expected Execution Version */
            expected_execution_version: number;
        };
        /** ExtractionOperationReference */
        ExtractionOperationReference: {
            /**
             * Evidence Id
             * Format: uuid
             */
            evidence_id: string;
            /**
             * Operation Id
             * Format: uuid
             */
            operation_id: string;
            /** Poll Url */
            poll_url: string;
            /** Replayed */
            replayed: boolean;
            /** Status */
            status: string;
        };
        /**
         * FactGrantRequest
         * @description One fact's content permission. Never identity permission, whatever the scope says.
         */
        FactGrantRequest: {
            /** Allow Safe Transformation */
            allow_safe_transformation: boolean;
            /**
             * Fact Id
             * Format: uuid
             */
            fact_id: string;
            /**
             * Max Scope
             * @enum {string}
             */
            max_scope: "INTERNAL_ONLY" | "AGGREGATE_ONLY" | "ANONYMOUS_CASE" | "NAMED_CASE" | "EXTERNAL_ACTION";
        };
        /**
         * FactPermissionResponse
         * @description One fact row. ``wording`` is contributor-facing text, never the fact's own value.
         */
        FactPermissionResponse: {
            /** Allow Safe Transformation */
            allow_safe_transformation: boolean;
            /** Current Scope */
            current_scope: string;
            /**
             * Fact Id
             * Format: uuid
             */
            fact_id: string;
            /** Fact Type */
            fact_type: string;
            /** Locked Reason */
            locked_reason: string | null;
            /** Policy Maximum Scope */
            policy_maximum_scope: string;
            /** Proposed Scope */
            proposed_scope: string;
            /** Requires Identity Grant */
            requires_identity_grant: boolean;
            /** Wording */
            wording: string;
        };
        /** FactResponse */
        FactResponse: {
            /**
             * Contributor Id
             * Format: uuid
             */
            contributor_id: string;
            /** Evidence Ids */
            evidence_ids: string[];
            /** Evidence Status */
            evidence_status: string;
            /**
             * Fact Id
             * Format: uuid
             */
            fact_id: string;
            /** Fact Type */
            fact_type: string;
            /** Sensitivity */
            sensitivity: string;
            /** Source Message Ids */
            source_message_ids: string[];
            /** Status */
            status: string;
            /** Value Preview */
            value_preview: string;
            /** Version */
            version: number;
        };
        /** FeedItemResponse */
        FeedItemResponse: {
            /** Attachment Thumbnails */
            attachment_thumbnails: components["schemas"]["AttachmentThumbnailResponse"][];
            chorus_signal: components["schemas"]["ChorusSignalResponse"] | null;
            /**
             * Message Id
             * Format: uuid
             */
            message_id: string;
            /** Pseudonym */
            pseudonym: string | null;
            /**
             * Sent At
             * Format: date-time
             */
            sent_at: string;
            /** Text */
            text: string;
        };
        /** FeedResponse */
        FeedResponse: {
            /** Items */
            items: components["schemas"]["FeedItemResponse"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** FindingResponse */
        FindingResponse: {
            /** Evidence Status */
            evidence_status: string;
            /**
             * Fact Id
             * Format: uuid
             */
            fact_id: string;
            /** Reason Code */
            reason_code: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IdentityGrantRequest
         * @description Identity permission, submitted as its own object and evaluated on its own.
         */
        IdentityGrantRequest: {
            /** Externally Shareable */
            externally_shareable: boolean;
            /**
             * Max Scope
             * @enum {string}
             */
            max_scope: "INTERNAL_ONLY" | "AGGREGATE_ONLY" | "ANONYMOUS_CASE" | "NAMED_CASE" | "EXTERNAL_ACTION";
        };
        /** IdentityPermissionResponse */
        IdentityPermissionResponse: {
            /** Externally Shareable */
            externally_shareable: boolean;
            /** Max Scope */
            max_scope: string;
            /** Policy Maximum Scope */
            policy_maximum_scope: string;
        };
        /** IncludedFactBody */
        IncludedFactBody: {
            /** Export Fact Ids */
            export_fact_ids: string[];
            /**
             * Fact Id
             * Format: uuid
             */
            fact_id: string;
        };
        /**
         * IngestAttachmentRequest
         * @description Attachment provenance declared by the adapter; bytes are never posted here.
         */
        IngestAttachmentRequest: {
            /** Byte Length */
            byte_length: number;
            /**
             * Evidence Id
             * Format: uuid
             */
            evidence_id: string;
            /** Media Type */
            media_type: string;
            /** Sha256 */
            sha256: string;
        };
        /** IngestMessageRequest */
        IngestMessageRequest: {
            /**
             * Adapter
             * @default SYNTHETIC
             * @constant
             */
            adapter: "SYNTHETIC";
            /**
             * Attachments
             * @default []
             */
            attachments: components["schemas"]["IngestAttachmentRequest"][];
            /** Channel Message Id */
            channel_message_id: string;
            /** Contributor Id */
            contributor_id?: string | null;
            /**
             * Sent At
             * Format: date-time
             */
            sent_at: string;
            /** Text */
            text: string;
        };
        /** IngestMessagesRequest */
        IngestMessagesRequest: {
            /**
             * Community Id
             * Format: uuid
             */
            community_id: string;
            /** Messages */
            messages: components["schemas"]["IngestMessageRequest"][];
        };
        /** IngestMessagesResponse */
        IngestMessagesResponse: {
            /** Accepted Count */
            accepted_count: number;
            /** Messages */
            messages: components["schemas"]["IngestedMessageResponse"][];
            operation: components["schemas"]["OperationReference"];
            /** Replayed Count */
            replayed_count: number;
        };
        /** IngestedMessageResponse */
        IngestedMessageResponse: {
            /** Channel Message Id */
            channel_message_id: string;
            /**
             * Message Id
             * Format: uuid
             */
            message_id: string;
            /** Replay */
            replay: boolean;
        };
        /**
         * InvalidationRequest
         * @description Withdraw an approval, or clear a terminal failure. The same body serves both.
         */
        InvalidationRequest: {
            /** Expected Execution Version */
            expected_execution_version: number;
            /** Proposal Hash */
            proposal_hash: string;
        };
        /** InvalidationResponse */
        InvalidationResponse: {
            /**
             * Action Id
             * Format: uuid
             */
            action_id: string;
            /** Authorization Version */
            authorization_version: number;
            /** Case State */
            case_state: string;
            /** Case Version */
            case_version: number;
            /**
             * Execution Id
             * Format: uuid
             */
            execution_id: string;
            /** Execution State */
            execution_state: string;
            /** Execution Version */
            execution_version: number;
            /** Pointer Status */
            pointer_status: string;
            /** Reason Code */
            reason_code: string;
        };
        /** InvestigationCaseResponse */
        InvestigationCaseResponse: {
            /** Authorization Version */
            authorization_version: number;
            /**
             * Case Id
             * Format: uuid
             */
            case_id: string;
            /** Corroboration Source Count */
            corroboration_source_count: number;
            /** State */
            state: string;
            /** Title */
            title: string;
            /** Version */
            version: number;
        };
        /** InvestigationResponse */
        InvestigationResponse: {
            assessment: components["schemas"]["AssessmentResponse"] | null;
            case: components["schemas"]["InvestigationCaseResponse"];
            compile: components["schemas"]["CompileExplanationResponse"] | null;
            /** Facts */
            facts: components["schemas"]["FactResponse"][];
            /** Reports */
            reports: components["schemas"]["ReportResponse"][];
        };
        /**
         * MandateDecisionRequest
         * @description One contributor's complete answer to one exact mandate version.
         *
         *     ``fact_grants`` is the **whole** replacement set for ``ADJUST``, never a patch. A body that
         *     listed one fact would otherwise mean "change this one" to a reader and "revoke all the
         *     others" to the server, and the two readings differ by everything.
         */
        MandateDecisionRequest: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "APPROVE" | "ADJUST" | "REFUSE" | "REVOKE";
            /** Expected Version */
            expected_version: number;
            /** Expires At */
            expires_at?: string | null;
            /**
             * Fact Grants
             * @default []
             */
            fact_grants: components["schemas"]["FactGrantRequest"][];
            identity_grant: components["schemas"]["IdentityGrantRequest"];
        };
        /** MandateDecisionResponse */
        MandateDecisionResponse: {
            /** Case State */
            case_state: string;
            /** Case Version */
            case_version: number;
            /** Decided At */
            decided_at: string | null;
            /**
             * Mandate Id
             * Format: uuid
             */
            mandate_id: string;
            /** Revoked At */
            revoked_at: string | null;
            /** Status */
            status: string;
            /** Supersedes Version */
            supersedes_version: number | null;
            /** Terms Hash */
            terms_hash: string;
            /** Version */
            version: number;
        };
        /** MandateThreadResponse */
        MandateThreadResponse: {
            /** Allowed Destination Ids */
            allowed_destination_ids: string[];
            /** Allowed Purposes */
            allowed_purposes: string[];
            /**
             * Case Id
             * Format: uuid
             */
            case_id: string;
            /** Case State */
            case_state: string;
            /**
             * Contributor Id
             * Format: uuid
             */
            contributor_id: string;
            /** Current Version */
            current_version: number;
            /** Decided At */
            decided_at: string | null;
            /** Expires At */
            expires_at: string | null;
            /** Fact Permissions */
            fact_permissions: components["schemas"]["FactPermissionResponse"][];
            /** History */
            history: components["schemas"]["MandateVersionResponse"][];
            identity_permission: components["schemas"]["IdentityPermissionResponse"];
            /**
             * Mandate Id
             * Format: uuid
             */
            mandate_id: string;
            /**
             * Proposed At
             * Format: date-time
             */
            proposed_at: string;
            /** Revoked At */
            revoked_at: string | null;
            /** Status */
            status: string;
            /** Terms Hash */
            terms_hash: string;
            /**
             * Valid From
             * Format: date-time
             */
            valid_from: string;
        };
        /** MandateVersionRefBody */
        MandateVersionRefBody: {
            /**
             * Mandate Id
             * Format: uuid
             */
            mandate_id: string;
            /** Terms Hash */
            terms_hash: string;
            /** Version */
            version: number;
        };
        /** MandateVersionResponse */
        MandateVersionResponse: {
            /** Decided At */
            decided_at: string | null;
            /** Revoked At */
            revoked_at: string | null;
            /** Status */
            status: string;
            /** Supersedes Version */
            supersedes_version: number | null;
            /** Terms Hash */
            terms_hash: string;
            /** Version */
            version: number;
        };
        /** OperationReference */
        OperationReference: {
            /**
             * Operation Id
             * Format: uuid
             */
            operation_id: string;
            /** Poll Url */
            poll_url: string;
            /** Status */
            status: string;
        };
        /** OperationResponse */
        OperationResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Code */
            error_code: string | null;
            /** Kind */
            kind: string;
            /**
             * Operation Id
             * Format: uuid
             */
            operation_id: string;
            /** Result Refs */
            result_refs: string[];
            /** Status */
            status: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PrivacyCountsResponse */
        PrivacyCountsResponse: {
            /**
             * Compile Id
             * Format: uuid
             */
            compile_id: string;
            /** Denied By Reason */
            denied_by_reason: {
                [key: string]: number;
            };
            /** Excluded */
            excluded: number;
            /** Included */
            included: number;
        };
        /**
         * ProposeActionRequest
         * @description Exactly the three values a caller genuinely chooses.
         *
         *     ``view_id`` and ``view_hash`` together are not redundant with the current pointer: they are
         *     what the caller *believes* is current, so a request made against a view a compile has since
         *     replaced is refused as stale rather than silently proposed against the newer one.
         */
        ProposeActionRequest: {
            /** Expected Case Version */
            expected_case_version: number;
            /** View Hash */
            view_hash: string;
            /**
             * View Id
             * Format: uuid
             */
            view_id: string;
        };
        /**
         * ProposeMandatesRequest
         * @description Accept one candidate case. It says nothing about what may be disclosed.
         */
        ProposeMandatesRequest: {
            /** Expected Case Version */
            expected_case_version: number;
        };
        /** ProposeMandatesResponse */
        ProposeMandatesResponse: {
            /**
             * Case Id
             * Format: uuid
             */
            case_id: string;
            /** Case Version */
            case_version: number;
            /** Proposals */
            proposals: components["schemas"]["ProposedMandateResponse"][];
            /** State */
            state: string;
        };
        /** ProposedMandateResponse */
        ProposedMandateResponse: {
            /**
             * Contributor Id
             * Format: uuid
             */
            contributor_id: string;
            /** Fact Grant Count */
            fact_grant_count: number;
            /**
             * Mandate Id
             * Format: uuid
             */
            mandate_id: string;
            /** Status */
            status: string;
            /** Terms Hash */
            terms_hash: string;
            /** Version */
            version: number;
        };
        /**
         * RenderedPreviewProjection
         * @description The regenerated bodies and the digest the proposal committed.
         *
         *     ``preview_hash`` is the *committed* value and ``matches_committed_hash`` says whether the
         *     bytes above still hash to it. Two fields rather than one, because "these are the bytes" and
         *     "these are the bytes that were approved" are different claims.
         */
        RenderedPreviewProjection: {
            /** Html Body */
            html_body: string;
            /** Matches Committed Hash */
            matches_committed_hash: boolean;
            /** Preview Hash */
            preview_hash: string;
            /** Template Version */
            template_version: string;
            /** Text Body */
            text_body: string;
        };
        /** ReportResponse */
        ReportResponse: {
            /**
             * Contributor Id
             * Format: uuid
             */
            contributor_id: string;
            /** Created At */
            created_at: string;
            /**
             * Report Id
             * Format: uuid
             */
            report_id: string;
            /** Status */
            status: string;
        };
        /** RequestedFactBody */
        RequestedFactBody: {
            /**
             * Fact Id
             * Format: uuid
             */
            fact_id: string;
            /**
             * Intended Usage
             * @enum {string}
             */
            intended_usage: "CLAIM" | "AGGREGATION_INPUT" | "EVIDENCE";
            /**
             * Necessity
             * @enum {string}
             */
            necessity: "REQUIRED" | "OPTIONAL";
        };
        /** ResetContributorResponse */
        ResetContributorResponse: {
            /** Actor */
            actor: string;
            /**
             * Contributor Id
             * Format: uuid
             */
            contributor_id: string;
            /** Pseudonym */
            pseudonym: string;
        };
        /** ResetCountsResponse */
        ResetCountsResponse: {
            /** Contributors */
            contributors: number;
            /** Deleted */
            deleted: number;
            /** Evidence */
            evidence: number;
            /** Messages */
            messages: number;
        };
        /** ResetEvidenceResponse */
        ResetEvidenceResponse: {
            /**
             * Evidence Id
             * Format: uuid
             */
            evidence_id: string;
            /** Media Type */
            media_type: string;
            /** Sha256 */
            sha256: string;
        };
        /** ResetRequest */
        ResetRequest: {
            /** Confirm */
            confirm: string;
            /** Namespace */
            namespace: string;
            /** Seed Version */
            seed_version: string;
        };
        /** ResetResponse */
        ResetResponse: {
            /**
             * Audit Event Id
             * Format: uuid
             */
            audit_event_id: string;
            /**
             * Community Id
             * Format: uuid
             */
            community_id: string;
            /** Contributors */
            contributors: components["schemas"]["ResetContributorResponse"][];
            /** Corpus Sha256 */
            corpus_sha256: string;
            counts: components["schemas"]["ResetCountsResponse"];
            /** Destination Id */
            destination_id: string;
            /** Evidence */
            evidence: components["schemas"]["ResetEvidenceResponse"][];
            /** Logical Now */
            logical_now: string;
            /** Namespace */
            namespace: string;
            /** Replayed */
            replayed: boolean;
            /**
             * Reset Id
             * Format: uuid
             */
            reset_id: string;
            /** Seed Version */
            seed_version: string;
        };
        /** SafeDestinationBody */
        SafeDestinationBody: {
            /** Destination Id */
            destination_id: string;
            /** Display Label */
            display_label: string;
            /** Kind */
            kind: string;
            /** Registry Version */
            registry_version: number;
            /**
             * Routing Token
             * Format: uuid
             */
            routing_token: string;
        };
        /** SessionResponse */
        SessionResponse: {
            /** Actor */
            actor: string;
            /** Capabilities */
            capabilities: string[];
            /**
             * Community Id
             * Format: uuid
             */
            community_id: string;
            /** Contributor Id */
            contributor_id: string | null;
            /** Namespace */
            namespace: string;
        };
        /**
         * ShareableCaseViewBody
         * @description The safe artifact, rendered field for field. Nothing is added and nothing is dropped.
         *
         *     Both counters appear, and they mean different things: ``case_version`` is the Core OCC
         *     version the view was built beside and is provenance only, while ``authorization_version``
         *     is the epoch the view is valid against and is what a caller compares before proposing
         *     against it (ADR-020 § 4).
         */
        ShareableCaseViewBody: {
            /** Audit Refs */
            audit_refs: string[];
            /** Authorization Snapshot Hash */
            authorization_snapshot_hash: string;
            /** Authorization Version */
            authorization_version: number;
            /**
             * Case Id
             * Format: uuid
             */
            case_id: string;
            /** Case Version */
            case_version: number;
            /** Community Public Label */
            community_public_label: string;
            /** Compiler Version */
            compiler_version: string;
            destination: components["schemas"]["SafeDestinationBody"];
            /** Expires At */
            expires_at: string;
            /** Generated At */
            generated_at: string;
            /** Mandate Version Set */
            mandate_version_set: components["schemas"]["MandateVersionRefBody"][];
            /** Policy Version */
            policy_version: string;
            /** Purpose */
            purpose: string;
            /** Safe Evidence Refs */
            safe_evidence_refs: components["schemas"]["ShareableEvidenceRefBody"][];
            /** Schema Version */
            schema_version: string;
            /** Shareable Facts */
            shareable_facts: components["schemas"]["ShareableFactBody"][];
            /** View Hash */
            view_hash: string;
            /**
             * View Id
             * Format: uuid
             */
            view_id: string;
        };
        /** ShareableEvidenceRefBody */
        ShareableEvidenceRefBody: {
            /** Caption */
            caption: string;
            /** Content Hash */
            content_hash: string;
            /** Created By Rule Id */
            created_by_rule_id: string;
            /**
             * Export Handle Id
             * Format: uuid
             */
            export_handle_id: string;
            /** Media Type */
            media_type: string;
            /**
             * Safe Evidence Ref Id
             * Format: uuid
             */
            safe_evidence_ref_id: string;
            /** Sha256 */
            sha256: string;
        };
        /** ShareableFactBody */
        ShareableFactBody: {
            /** Content Hash */
            content_hash: string;
            /** Contributor Count */
            contributor_count: number;
            /** Effective Scope */
            effective_scope: string;
            /** Evidence Status */
            evidence_status: string;
            /**
             * Export Fact Id
             * Format: uuid
             */
            export_fact_id: string;
            /** Fact Type */
            fact_type: string;
            /** Safe Evidence Ref Ids */
            safe_evidence_ref_ids: string[];
            /** Safe Text */
            safe_text: string;
            /** Transformation */
            transformation: string;
            /** Transformation Rule Id */
            transformation_rule_id: string;
        };
        /** StartInvestigationRequest */
        StartInvestigationRequest: {
            /** Expected Case Version */
            expected_case_version: number;
            /**
             * Reason
             * @enum {string}
             */
            reason: "INITIAL" | "NEW_EVIDENCE" | "REOPEN";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VerificationView */
        VerificationView: {
            /** Action Pointer Invalidated */
            action_pointer_invalidated: boolean;
            /** Case State */
            case_state: string;
            /** Case Version */
            case_version: number;
            /**
             * Commitment Id
             * Format: uuid
             */
            commitment_id: string;
            /** Commitment Status */
            commitment_status: string;
            /** Commitment Version */
            commitment_version: number;
        };
        /**
         * VerifyCommitmentRequest
         * @description The frozen verification body. There is deliberately no contributor field.
         */
        VerifyCommitmentRequest: {
            /** Expected Version */
            expected_version: number;
            /** Fixture Evidence Id */
            fixture_evidence_id?: string | null;
            /** Note */
            note?: string | null;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "FULFILLED" | "MISSED";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_case_v1_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Chorus-Demo-Actor"?: string | null;
            };
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseSurfaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    propose_action_v1_cases__case_id__actions_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-Chorus-Demo-Actor"?: string | null;
            };
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposeActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationReference"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_action_v1_cases__case_id__actions__action_id__approvals_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-Chorus-Demo-Actor"?: string | null;
            };
            path: {
                case_id: string;
                action_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_execution_v1_cases__case_id__actions__action_id__executions_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-Chorus-Demo-Actor"?: string | null;
            };
            path: {
                case_id: string;
                action_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecutionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationReference"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invalidate_action_v1_cases__case_id__actions__action_id__invalidation_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-Chorus-Demo-Actor"?: string | null;
            };
            path: {
                case_id: string;
                action_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvalidationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvalidationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_case_audit_v1_cases__case_id__audit_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: {
                "X-Chorus-Demo-Actor"?: string | null;
            };
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_commitment_v1_cases__case_id__commitments__commitment_id__verification_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-Chorus-Demo-Actor"?: string | null;
            };
            path: {
                case_id: string;
                commitment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyCommitmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_investigation_v1_cases__case_id__investigation_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Chorus-Demo-Actor"?: string | null;
            };
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_investigation_v1_cases__case_id__investigations_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-Chorus-Demo-Actor"?: string | null;
            };
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartInvestigationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationReference"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    propose_mandates_v1_cases__case_id__mandates_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-Chorus-Demo-Actor"?: string | null;
            };
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposeMandatesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposeMandatesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_mandate_v1_cases__case_id__mandates__mandate_id__decisions_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-Chorus-Demo-Actor"?: string | null;
            };
            path: {
                case_id: string;
                mandate_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MandateDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MandateDecisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compile_view_v1_cases__case_id__views_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-Chorus-Demo-Actor"?: string | null;
            };
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompileViewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompileViewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_current_mandate_v1_contributors__contributor_id__mandates_current_get: {
        parameters: {
            query: {
                case_id: string;
            };
            header?: {
                "X-Chorus-Demo-Actor"?: string | null;
            };
            path: {
                contributor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MandateThreadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    advance_demo_clock_v1_demo_clock_advance_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Chorus-Demo-Actor"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdvanceDemoClockRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoClockView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_demo_corpus_v1_demo_corpus_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Chorus-Demo-Actor"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoCorpusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deliver_external_reply_v1_demo_external_replies_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-Chorus-Demo-Actor"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeliverFixtureReplyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionOperationReference"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_demo_v1_demo_reset_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                "X-Chorus-Demo-Actor"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_feed_v1_feed_get: {
        parameters: {
            query: {
                community_id: string;
                limit?: number;
                cursor?: string | null;
            };
            header?: {
                "X-Chorus-Demo-Actor"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_messages_v1_ingest_messages_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-Chorus-Demo-Actor"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestMessagesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestMessagesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_operation_v1_operations__operation_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Chorus-Demo-Actor"?: string | null;
            };
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_session_v1_session_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Chorus-Demo-Actor"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
